#!/usr/bin/env python3
"""Render library-reference tables and maxima from the same raw report records."""
import argparse
import json
import math
from pathlib import Path

LABELS = {'sonatina':'Sonatina','virtuosity':'Virtuosity','shiny':'Shinyguitar',
          'bass':'Black and Blue bass','standard':'Standard Guitar','metal':'METAL-GTX'}

def render(report, ledger_db, gain_limit_db=0.1, cases=None):
    labels = LABELS if cases is None else {name: LABELS.get(name,name) for name in cases}
    rows = []
    valid = []
    incomplete = []
    for name in labels:
        case = report.get('cases', {}).get(name)
        residual = None
        status = 'missing case'
        if case:
            native, reference = case.get('native', {}), case.get('aria', {})
            left, right = native.get('metrics', {}), reference.get('metrics', {})
            if native.get('exit') != 0 or reference.get('exit') != 0:
                status = 'execution failed or missing'
            elif not left or not right:
                status = 'missing metrics'
            elif left.get('channels') != right.get('channels'):
                status = 'unequal channel aggregation; comparison invalid'
            elif left.get('rate') != right.get('rate'):
                status = 'unequal sample rate; comparison invalid'
            else:
                a, b = left.get('sustain_rms'), right.get('sustain_rms')
                if not isinstance(a, (int,float)) or not isinstance(b, (int,float)):
                    status = 'missing RMS'
                elif not math.isfinite(a) or not math.isfinite(b) or a <= 0 or b <= 0:
                    status = 'silent or nonfinite RMS; comparison invalid'
                else:
                    residual = 20 * math.log10(a / b) - ledger_db
                    valid.append((name, residual))
                    status = case.get('classification', 'whole-patch diagnostic; selection/component attribution open')
        if residual is None:
            incomplete.append(name)
        program = Path(case.get('entry','')).name if case else '—'
        key = case.get('midi',{}).get('key','—') if case else '—'
        number = f'{residual:+.4f}' if residual is not None else '—'
        rows.append(f'| {labels[name]} | `{program}` | {key} | {number} | {status} |')
    lines = ['<!-- Generated by tools/sfz-reference-report.py from the final report. -->',
             '| Family | Original entry program | Musical key | Historical aggregate residual dB | Classification |',
             '|---|---|---:|---:|---|', *rows, '']
    if valid:
        worst = max(valid, key=lambda item: abs(item[1]))
        lines.append(f'The largest valid absolute residual is {abs(worst[1]):.4f} dB ({labels[worst[0]]}).')
    else:
        lines.append('No valid numeric residual is available.')
    lines.append(f'The explicit ARIA ledger is {ledger_db:.10f} dB; the isolated plain-gain bound is {gain_limit_db:.4f} dB and does not classify whole patches.')
    if incomplete:
        lines.append('Incomplete or invalid comparisons: '+', '.join(labels[name] for name in incomplete)+'.')
    lines += ['This whole-patch table does not establish isolated gain, selected-sample parity, pitch,',
              'envelope, release, filter or stochastic-distribution conformance. Differences require',
              'source/selection attribution; an unexplained difference is an open gate, not a pass.', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', type=Path, required=True)
    parser.add_argument('--ledger-db', type=float, required=True,
                        help='independently calibrated constant; never fit to these rows')
    parser.add_argument('--gain-limit-db', type=float, default=0.1)
    parser.add_argument('--output', type=Path)
    parser.add_argument('--cases', nargs='+', help='explicit experiment case names; default requires all six library families')
    args = parser.parse_args()
    result = render(json.loads(args.report.read_text()), args.ledger_db, args.gain_limit_db, args.cases)
    if args.output:
        args.output.write_text(result)
    else:
        print(result)
